enum Macro {
  MANUFACTURER_DURABLE_GOODS = 'DGORDER',
  MANUFACTURER_CONSUMER_DURABLE_GOODS = 'ACDGNO',
  PERSONAL_DURABLE_GOODS_MOTOR_VEHICLES_AND_PARTS = 'DMOTRC1Q027SBEA',
  INDUSTRIAL_DURABLE_CONSUMER_GOODS = 'IPDCONGD'
}

export default Macro;
